import tkinter as tk
import functools
import sys
import mysql.connector as mc
root=tk.Tk()
root.title("vipul")
rw=root.winfo_screenwidth()
rh=root.winfo_screenheight()
root.geometry(("%dx%d")%(rw,rh))
root.configure(background='#856f32')
def database():
	conn=mc.connect(host='localhost',user='root',password='',port='3307',database='info_gui')
	curs=conn.cursor()
	curs.execute("insert into tab_gui values('%s','%s')"%(name.get(),hash(passwd.get())))
	conn.commit()
def create_new_win():
	database()
	newwin=tk.Toplevel(root)
	newwin.title("new window")
	note="Hello "+name.get()
	labelfont=('Courier', 50, 'bold')
	display=tk.Label(newwin,text=note,width='60')
	display.config(bg='green',fg='yellow')
	display.config(font=labelfont)
	display.config(height=3, width=20)
	display.place(x=100,y=200)
	newwin.geometry(("%dx%d")%(rw,rh))
	newwin.configure(background='green')
header=tk.Label(root,text="Railway Reservation System",width='60')
headerfont=('Courier',40,'bold')
header.config(font=headerfont)
header.config(fg='blue')
header.place(x=300,y=400)
tk.Label(root,text="enter name:").grid(row=2,column=0)
name=tk.Entry(root)
name.grid(row=2,column=1)
tk.Label(root,text="Enter password:").grid(row=3,column=0)
passwd=tk.Entry(root,show='*',width=50)
passwd.grid(row=3,column=1)
action=functools.partial(create_new_win)
but=tk.Button(root,bg='pink',height=5,width=10,text='Press me!!',command=action)
but.grid(row=2)
root.mainloop()

